sudo: required
services:
  - docker

before_install:
  - docker build -t  haryorbami/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run haryorbami/react-test npm test -- --coverage

after_success:
  - docker build -t haryorbami/multi-client ./client
  - docker build -t haryorbami/multi-nginx ./nginx
  - docker build -t haryorbami/multi-server ./server
  - docker build -t haryorbami/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push haryorbami/multi-client
  - docker push haryorbami/multi-nginx
  - docker push haryorbami/multi-server
  - docker push haryorbami/multi-worker
