sudo: required
services:
  - docker

before_install:
  - docker build -t  fatanmi/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run fatanmi/react-test npm test -- --coverage

after_success:
  - docker build -t fatanmi/multi-client ./client
  - docker build -t fatanmi/multi-nginx ./nginx
  - docker build -t fatanmi/multi-server ./server
  - docker build -t fatanmi/multi-worker ./worker
 
  